name: Build ARM64 Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
          
      - name: Clean go mod cache
        run: |
          rm -f go.sum
          go clean -modcache
          
      - name: Update go.mod
        run: |
          sed -i 's/go 1.23.3/go 1.23.4/' go.mod
          
      - name: Get dependencies
        run: |
          go mod tidy
          go get github.com/joho/godotenv
          go get github.com/nfnt/resize
          go get github.com/bincooo/edge-api@v1.0.4-0.20241209140454-b708b5d57059
          
      - name: Install iocgo
        run: go install ./cmd/iocgo
        
      - name: Build ARM64 binary
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0
        run: go build -toolexec iocgo -o server-arm64 ./main.go
        
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: server-arm64
          path: server-arm64
