# .github/workflows/build.yml
name: Build ARM64 Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'  # Specify a stable version
          
      - name: Update dependencies
        run: |
          go mod tidy
          go get github.com/bincooo/emit.io@latest
          go get github.com/bincooo/coze-api@latest
          go get github.com/bincooo/you.com@latest
          
      - name: Install iocgo
        run: go install ./cmd/iocgo
        
      - name: Build ARM64 binary
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0
        run: go build -toolexec iocgo -o server-arm64 ./main.go
        
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: server-arm64
          path: server-arm64
