# .github/workflows/build.yml
name: Build ARM64 Binary

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Adjust version as needed
          
      - name: Install iocgo
        run: go install ./cmd/iocgo
        
      - name: Build ARM64 binary
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -toolexec iocgo -o server-arm64 ./main.go
        
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: server-arm64
          path: server-arm64
